name: create-release

on:
  push:
    tags:
      - "x*"

jobs:
  create-release:
      steps:
  
      - uses: actions/checkout@v2
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        run: echo TAG - ${GITHUB_REF/refs\/tags\//}
        run: hub release create -pd ${GITHUB_REF/refs\/tags\//}
